create table if not exists public.wallet (
  id integer primary key default 1 check (id = 1),
  balance numeric not null default 500
);

create table if not exists public.recipients (
  id bigint generated by default as identity primary key,
  name text not null unique,
  wallet text not null
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  recipient text not null,
  amount numeric not null,
  type text not null check (type in ('send', 'receive')),
  created_at timestamptz not null default now()
);

create table if not exists public.bank_accounts (
  id bigint generated by default as identity primary key,
  user_id uuid not null default gen_random_uuid(),
  bank_name text not null,
  account_number text not null,
  account_name text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.offramp_transactions (
  id bigint generated by default as identity primary key,
  bank_account_id bigint not null references public.bank_accounts(id),
  amount numeric not null,
  naira_amount numeric not null,
  rate numeric not null,
  status text not null default 'pending' check (status in ('pending', 'processing', 'completed', 'failed')),
  reference text unique,
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null default gen_random_uuid(),
  title text not null,
  message text not null,
  type text not null check (type in ('incoming', 'insight', 'warning', 'transaction')),
  status text not null default 'unread' check (status in ('unread', 'read')),
  action_url text,
  metadata jsonb default '{}',
  created_at timestamptz not null default now()
);

create index if not exists idx_bank_accounts_user_id on public.bank_accounts(user_id);
create index if not exists idx_offramp_transactions_bank_account_id on public.offramp_transactions(bank_account_id);
create index if not exists idx_notifications_user_id on public.notifications(user_id);
create index if not exists idx_notifications_created_at on public.notifications(created_at desc);
create index if not exists idx_notifications_status on public.notifications(status);

insert into public.wallet (id, balance)
values (1, 500)
on conflict (id) do nothing;

insert into public.recipients (name, wallet)
values
  ('john', 'GCFX123456789'),
  ('sarah', 'GABCD456789'),
  ('david', 'GXYZW789012'),
  ('divine', 'GCFX2983746510')
on conflict (name) do nothing;
