create table if not exists public.wallet (
  id integer primary key default 1 check (id = 1),
  balance numeric not null default 500
);

create table if not exists public.recipients (
  id bigint generated by default as identity primary key,
  name text not null unique,
  wallet text not null
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  recipient text not null,
  amount numeric not null,
  type text not null check (type in ('send', 'receive')),
  created_at timestamptz not null default now()
);

insert into public.wallet (id, balance)
values (1, 500)
on conflict (id) do nothing;

insert into public.recipients (name, wallet)
values
  ('john', 'GCFX123456789'),
  ('sarah', 'GABCD456789'),
  ('david', 'GXYZW789012'),
  ('divine', 'GCFX2983746510')
on conflict (name) do nothing;
